# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- preview

jobs:
- job: Job_1
  displayName: Agent job 1
  timeoutInMinutes: 20
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    fetchTags: false
    
  - task: NodeTool@0
    inputs:
      versionSpec: '16.17.1'
    displayName: 'Install Node.js'

  - task: NodeTool@0
    displayName: Use Node 16.17.1
    inputs:
      versionSpec: 16.17.1
  
  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false

  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      verbose: false
      customCommand: run build-dev

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist/*'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
      verbose: true

  - task: PublishBuildArtifacts@1




